# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-05-20 10:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200520_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 20, 15, 57, 26, 590430), editable=False),
        ),
        migrations.AlterField(
            model_name='employerdetails',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 20, 15, 57, 26, 589431), editable=False),
        ),
        migrations.AlterField(
            model_name='employerdetails',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 20, 15, 57, 26, 589431), editable=False),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 20, 15, 57, 26, 591430), editable=False),
        ),
    ]
