# Generated by Django 2.1.7 on 2020-05-20 17:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20200520_1815'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.AlterField(
            model_name='application',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 20, 23, 14, 0, 689952), editable=False),
        ),
        migrations.AlterField(
            model_name='employerdetails',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 20, 23, 14, 0, 689952), editable=False),
        ),
        migrations.AlterField(
            model_name='employerdetails',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 20, 23, 14, 0, 689952), editable=False),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='company_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 20, 23, 14, 0, 689952), editable=False),
        ),
    ]
