# Generated by Django 2.1.7 on 2020-05-21 12:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20200520_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 21, 17, 43, 51, 101461), editable=False),
        ),
        migrations.AlterField(
            model_name='application',
            name='username',
            field=models.ForeignKey(max_length=200, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employerdetails',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 21, 17, 43, 51, 85838), editable=False),
        ),
        migrations.AlterField(
            model_name='employerdetails',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 21, 17, 43, 51, 85838), editable=False),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 21, 17, 43, 51, 101461), editable=False),
        ),
    ]
