# Generated by Django 2.1.7 on 2020-05-22 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20200521_2140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='description',
            new_name='describe_yourself',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='document',
            new_name='resume',
        ),
        migrations.AddField(
            model_name='employerdetails',
            name='our_offical_website',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='employerdetails',
            name='our_requirements',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 22, 20, 37, 10, 831188), editable=False),
        ),
        migrations.AlterField(
            model_name='employerdetails',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 22, 20, 37, 10, 829189), editable=False),
        ),
        migrations.AlterField(
            model_name='employerdetails',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 22, 20, 37, 10, 829189), editable=False),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 22, 20, 37, 10, 833187), editable=False),
        ),
    ]
