# Generated by Django 2.1.7 on 2020-05-22 21:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20200522_2037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employerdetails',
            old_name='own',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='application',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 23, 2, 40, 5, 758166), editable=False),
        ),
        migrations.AlterField(
            model_name='employerdetails',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 23, 2, 40, 5, 756164), editable=False),
        ),
        migrations.AlterField(
            model_name='employerdetails',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 23, 2, 40, 5, 756164), editable=False),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 23, 2, 40, 5, 759165), editable=False),
        ),
    ]
