# Generated by Django 2.1.7 on 2020-05-23 11:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20200523_0240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employerdetails',
            old_name='owner',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='application',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 23, 17, 6, 6, 43355), editable=False),
        ),
        migrations.AlterField(
            model_name='employerdetails',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 23, 17, 6, 6, 39356), editable=False),
        ),
        migrations.AlterField(
            model_name='employerdetails',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 23, 17, 6, 6, 39356), editable=False),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 23, 17, 6, 6, 47354), editable=False),
        ),
    ]
